MusicCenter.App/Controllers/BandController.cs
using MusicCenter.App.Filters;
using MusicCenter.Common.RequestModels;
using MusicCenter.Common.ViewModels.Band;
using MusicCenter.Services.Intefaces;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;

namespace MusicCenter.App.Controllers
{
    public class BandController : BaseController
    {
        IBandService bandService;

        public BandController(IBandService serv)
        {
            bandService = serv;
        }

        public PartialViewResult RenderBandLayout(string BandName)
        {
            return PartialView("_BandLayout", BandName);
        }

        [UserAuthorize]
        public ActionResult UserBands()
        {
            List<BandListItemViewModel> userBands = bandService.GetUserBandList(Session["user"].ToString());

            return View(userBands);
        }

        public ActionResult AddBand()
        {
            return View();
        }

        [HttpPost]
        [UserAuthorize]
        public ActionResult AddBand(AddBandViewModel model)
        {
            if (model.Avatar.PostedFile != null)
            {
                string trailingPath = model.Avatar.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Avatar.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid)
            {
                if (!bandService.IfBandExists(model.Name))
                {
                    model.UserEmail = Session["user"].ToString();
                    bandService.AddBand(model);
                }
            }

            return RedirectToAction("UserBands");
        }

        [BandAuthorize]
        public ActionResult GetBandPanel()
        {
            BandPanelViewModel model = new BandPanelViewModel();
            model = bandService.GetBandPanelViewModelByName(Session["band"].ToString());

            return PartialView("_BandPanel", model);
        }

        public ActionResult BandProfile(string BandName)
        {
            BandProfileViewModel model = bandService.GetBandProfileViewModel(BandName);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult BandProfile(BandProfileViewModel model)
        {
            if (model.Avatar.PostedFile != null)
            {
                string trailingPath = model.Avatar.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Avatar.RelativePathToSave = fullPath;
            }

            if (bandService.IsVisitorBandOwner(Session["band"].ToString(), model.BandId))
            {
                if (ModelState.IsValid)
                {
                    bandService.EditBandProfile(model);
                }
            }

            model = bandService.GetBandProfileViewModel(model.Name);

            return View(model);
        }

        public ActionResult BandAlbums(string BandName)
        {
            BandAlbumListViewModel albumList = bandService.GetBandAlbums(BandName);

            return View(albumList);
        }

        public ActionResult BandSingles(string BandName)
        {
            BandSingleListViewModel model = bandService.GetBandSingleListViewModel(BandName);

            return View(model);
        }


        [BandAuthorize]
        public ActionResult AddAlbum()
        {
            AddAlbumViewModel model = new AddAlbumViewModel();
            model.BandName = Session["band"].ToString();

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult AddAlbum(AddAlbumViewModel model)
        {
            if (model.Cover.PostedFile != null)
            {
                string trailingPath = model.Cover.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Cover.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid && model.SongsNames.Length > 0)
            {
                bandService.AddAlbum(model);
            }
            
            return View(model);
        }

        public ActionResult Album(string AlbumName)
        {
            AlbumViewModel model = bandService.GetAlbumViewModelByName(AlbumName);
 
            return View(model);
        }

        [HttpGet]
        [BandAuthorize]
        public ActionResult UpdateAlbum(string AlbumName)
        {
            UpdateAlbumViewModel model = bandService.GetUpdateAlbumViewModel(AlbumName);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult UpdateAlbum(UpdateAlbumViewModel model)
        {
            if (model.Cover.PostedFile != null)
            {
                string trailingPath = model.Cover.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Cover.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid)
            {
                bandService.UpdateAlbum(model);
            }

            model = bandService.GetUpdateAlbumViewModel(model.Name);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult DeleteAlbum(string AlbumName)
        {
            if (bandService.IsVisitorAlbumOwner(Session["band"].ToString(), AlbumName))
            {
                bandService.DeleteAlbum(AlbumName);
            }
            
            return RedirectToAction("BandAlbums");
        }

        [BandAuthorize]
        public ActionResult AddSingle()
        {
            AddSingleViewModel model = new AddSingleViewModel();
            model.BandName = Session["band"].ToString();

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult AddSingle(AddSingleViewModel model)
        {
            if (ModelState.IsValid && !String.IsNullOrEmpty(model.SongName))
            {
                bandService.AddSingle(model);
            }

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult DeleteSingle(int SingleId)
        {
            bandService.DeleteSingle(SingleId);

            return RedirectToAction("BandSingles");
        }

        [BandAuthorize]
        public ActionResult UpdateSingle(int SingleId)
        {
            BandSingleViewModel model = bandService.GetBandSingleViewModel(SingleId);
            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult UpdateSingle(BandSingleViewModel model)
        {
            if (ModelState.IsValid)
            {
                bandService.UpdateSingle(model);
            }
            model = bandService.GetBandSingleViewModel(model.Id);
            return View(model);
        }

        public JsonResult GetAllBandNames()
        {
            return Json(bandService.GetAllBandNames(), JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult GetBandsPanel()
        {
            List<BandsPanelViewModel> model = bandService.GetNewestBands();

            return PartialView("_BandsPanel", model);
        }

        public PartialViewResult GetAlbumsPanel()
        {
            List<AlbumsPanelViewModel> model = bandService.GetNewestAlbums();

            return PartialView("_AlbumsPanel", model);
        }

        public PartialViewResult GetSongsPanel()
        {
            List<SongsPanelViewModel> model = bandService.GetNewestSingles();

            return PartialView("_SongsPanel", model);
        }

        public ActionResult Single(int SingleId)
        {
            var model = bandService.GetBandSingleViewModel(SingleId);

            return View(model);
        }
        
        [HttpGet]
        public ActionResult BandList(int id = 1)
        {
            string dateFrom = this.Request.QueryString["DateFrom"];
            string dateTo = this.Request.QueryString["DateTo"];

            DataListFilterModel filter = new DataListFilterModel()
            {
                Names = this.Request.QueryString["Names"],
                GenreNames = this.Request.QueryString["GenreNames"],
                DateFrom = string.IsNullOrEmpty(dateFrom) ? (DateTime?)null : DateTime.Parse(dateFrom),
                DateTo = string.IsNullOrEmpty(dateTo) ? (DateTime?)null : DateTime.Parse(dateTo)
            };

            var model = bandService.GetBandListByPageNuber(filter, id);
            if (Request.IsAjaxRequest())
                return PartialView("_BandListPartial", model);
            return View(model);
        }

        [HttpGet]
        public ActionResult AlbumList(int id = 1)
        {
            string dateFrom = this.Request.QueryString["DateFrom"];
            string dateTo = this.Request.QueryString["DateTo"];

            DataListFilterModel filter = new DataListFilterModel()
            {
                Names = this.Request.QueryString["Names"],
                GenreNames = this.Request.QueryString["GenreNames"],
                DateFrom = string.IsNullOrEmpty(dateFrom) ? (DateTime?)null : DateTime.Parse(dateFrom),
                DateTo = string.IsNullOrEmpty(dateTo) ? (DateTime?)null : DateTime.Parse(dateTo)
            };

            var model = bandService.GetAlbumListByPageNuber(filter, id);

MusicCenter.App/Controllers/UserController.cs
using MusicCenter.App.Filters;
using MusicCenter.Common.ViewModels.Band;
using MusicCenter.Common.ViewModels.Message;
using MusicCenter.Common.ViewModels.User;
using MusicCenter.Services.Intefaces;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicCenter.App.Controllers
{
    public class UserController : BaseController
    {
        IUserService userService;

        public UserController(IUserService service)
        {
            userService = service;
        }

        [UserAuthorize]
        public ActionResult GetUserPanel()
        {
            UserPanelViewModel model = new UserPanelViewModel();
            model = userService.GerUserPanelViewModelByEmail(Session["user"].ToString());

            return PartialView("_UserPanel", model);
        }

        [UserAuthorize]
        public ActionResult UserProfile()
        {
            UserProfileViewModel model = userService.GetUserProfile(Session["user"].ToString());
            return View(model);
        }

        [UserAuthorize]
        [HttpPost]
        public ActionResult UserProfile(UserProfileViewModel model)
        {
            model.email = Session["user"].ToString();

            if (model.Avatar.PostedFile != null)
            {
                string trailingPath = model.Avatar.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Avatar.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid && userService.VerifyLoginAndPassword(model.email, model.OldPassword))
            {
                userService.UpdateUser(model);
            }

            UserProfileViewModel updatedUser = userService.GetUserProfile(Session["user"].ToString());

            return View(updatedUser);
        }

        [UserAuthorize]
        public ActionResult UserSoundcloudProfile()
        {
            UserSoundcloudProfileViewModel model = userService.GetUserSoundcloudProfile(Session["user"].ToString());

            return View(model);
        }

        [HttpPost]
        [UserAuthorize]
        public ActionResult UserSoundcloudProfile(UserSoundcloudProfileViewModel model)
        {
            model.email = Session["user"].ToString();

            if (model.Avatar.PostedFile != null)
            {
                string trailingPath = model.Avatar.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Avatar.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid)
            {
                userService.UpdateSoundCloudUser(model);
            }

            UserSoundcloudProfileViewModel updatedUser = userService.GetUserSoundcloudProfile(Session["user"].ToString());

            return View(updatedUser);
        }

    }
}

MusicCenter.App/Views/Shared/BandDetailsRemovable.cshtml
@model MusicCenter.Common.ViewModels.Concert.BandConcertViewModel

<div class="row" id="@Model.BandName">
    @Html.Hidden("Bands", @Model.BandName)
    <a href="@Url.Action("BandProfile", "Band", new {BandName = @Model.BandName })" style="">
        <div class="col-md-2">
            <img src="@Model.Avatar.PathToShow" class="img-circle" width="50" height="50" style="margin-left: 5px">
        </div>
        <div class="col-md-2">
            @Model.BandName
        </div>
        <div class="col-md-2">
            @foreach (var genre in Model.Genres)
            {
                <div style="display:inline">@genre </div>
            }
        </div>
        <div class="col-md-4">
            @Html.DisplayFor(m => m.CreationDate)
        </div>
    </a>
        <div class="col-md-2">
            <input type="button" name="RemoveBand" id="@Model.BandName" class="btn btn-default pull-right" value="@MusicCenter.Common.Resources.Global.Delete" />
        </div>
</div>








MusicCenter.App/Views/Shared/_AlbumTable.cshtml
@model PagedList<MusicCenter.Common.ViewModels.Band.AlbumListItemViewModel>

<div class="row">
    <div class="col-sm-2">

    </div>
    <div class="col-sm-2">
        @MusicCenter.Common.Resources.Global.Name
    </div>
    <div class="col-sm-2">
        @MusicCenter.Common.Resources.Global.Genres
    </div>
    <div class="col-sm-2">
        @MusicCenter.Common.Resources.Global.CreateDate
    </div>
</div>

@foreach (var album in Model)
{
    <div class="row">
        <a href="@Url.Action("Album", "Band", new { AlbumName = album.Name})" style="text-decoration: none;">
            <div class="col-sm-2">
                <img src="@album.Avatar.PathToShow" class="img-circle" width="50" height="50" style="margin-left: 5px">
            </div>
            <div class="col-sm-2">
                @album.Name
            </div>
            <div class="col-sm-2">
                @if (album.Genres != null)
                {
                    if (album.Genres.Count > 3)
                    {
                        <div>@String.Join(",", album.Genres.Take(3).ToArray())</div>
                    }
                    else
                    {
                        <div>@String.Join(",", album.Genres.ToArray())</div>
                    }
                }
            </div>
            <div class="col-sm-2">
                @Html.DisplayFor(m => album.CreationDate)
            </div>
        </a>
        @{
            var controllerName = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();

            if (Session["user"] != null && controllerName == "Band")
            {
                <div class="col-sm-2">
                    <input type="button" name="AddAlbumToFavBtn" data-albumname="@album.Name" class="btn btn-success" value="@MusicCenter.Common.Resources.Global.AddToFavourites" />
                </div>
            }
            else if (Session["user"] != null && controllerName == "Favourites")
            {
                <div class="col-sm-2">
                    <input type="button" name="DeleteAlbumFav" data-albumname="@album.Name" class="btn btn-danger" value="@MusicCenter.Common.Resources.Global.Delete" />
                </div>
            }

        }
    </div>
}
<div id="albumListData" data-user="@Session["user"]" data-addtofavurl="@Url.Action("AddAlbumToFavourites", "Favourites")" data-checkfavurl="@Url.Action("IsUserHaveAlbumsInFavourites", "Favourites")" />

MusicCenter.App/Views/Shared/_AlbumsPanel.cshtml
@model List<MusicCenter.Common.ViewModels.Band.AlbumsPanelViewModel>

<ul class="nav nav-tabs" style="margin-bottom:10px">
    <li role="presentation" class="active"><a href="#">@MusicCenter.Common.Resources.Global.NewAlbums</a></li>
</ul>

@if (Model != null)
{
    foreach (var album in Model)
    {
        <div class="col-sm-2 col-md-4">
        <a href="@Url.Action("Album", "Band", new { AlbumName = album.AlbumName })" style="text-decoration:none">
            <div class="thumbnail">
                <img src="@album.CoverPath" )" alt="...">
                <div class="caption">
                    <h3>@album.AlbumName</h3>
                    <p>@album.ReleaseDate</p>
                    <p>@album.Genres</p>
                </div>
            </div>
        </a>
    </div>
    }
}

MusicCenter.App/Views/Shared/_BandListPartial.cshtml
@model PagedList<MusicCenter.Common.ViewModels.Band.BandListItemViewModel>

@{ Html.RenderPartial("_BandTable", Model); }

<div style="bottom:0; position:fixed; width:100%; text-align:center;">
    @Ajax.Pager(Model, new PagerOptions { ActionName = "BandList", ControllerName = "Band", CurrentPagerItemTemplate = "<li class='active'><a href='#'>{0}</a></li>", DisabledPagerItemTemplate = "<li class='disabled'><a>{0}</a></li>", PageIndexParameterName = "id", FirstPageText = @MusicCenter.Common.Resources.Global.First, LastPageText = @MusicCenter.Common.Resources.Global.Last, NextPageText = @MusicCenter.Common.Resources.Global.Next, PrevPageText = @MusicCenter.Common.Resources.Global.Previous, ContainerTagName = "ul", CssClass = "pagination", PagerItemTemplate = "<li name='pagerPage'>{0}</li>" }).AjaxOptions(a => a.SetUpdateTargetId("dataList").SetDataFormId("dataFilterForm").SetOnSuccess("bandListScope.OnGridLoaded"))
</div>

MusicCenter.App/Views/Shared/_BandPanel.cshtml
@model MusicCenter.Common.ViewModels.Band.BandPanelViewModel

<form>
    <ul class="nav navbar-nav navbar-right" style="color: white">
        <li>
            @Html.ActionLink(@Model.Name, "BandProfile", "Band", new { BandName = @Model.Name}, new { style = "height: 15px" })
            @Html.ActionLink(@MusicCenter.Common.Resources.Global.NewMessages + @Model.MessagesCount, "BandMessages", "Message", null, new { style = "height: 15px; margin-bottom: 10px" })
        </li>
        <li>
            <img src="@Model.AvatarPath" class="img-circle" width="50" height="50" style="margin-left: 5px">
        </li>
        <li>
            @Html.ActionLink(MusicCenter.Common.Resources.Global.LogOut, "LogOutBand", "Account")
        </li>
    </ul>

</form>



MusicCenter.App/Views/Shared/_BandsPanel.cshtml
@model List<MusicCenter.Common.ViewModels.Band.BandsPanelViewModel>
</br>
<ul class="nav nav-tabs" style="margin-bottom:10px">
    <li role="presentation" class="active"><a href="#">@MusicCenter.Common.Resources.Global.NewBands</a></li>
</ul>

@if (Model != null)
{
    foreach (var band in Model)
    {
        <div class="col-sm-2 col-md-4">
            <a href="@Url.Action("BandProfile", "Band", new { BandName = band.BandName})" style="text-decoration: none;">
                <div class="thumbnail">
                    <img src="@band.AvatarPath" )" alt="...">
                    <div class="caption">
                        <h3>@band.BandName</h3>
                        <p>@band.Genres</p>
                        <p>@band.DescriptionPart</p>
                    </div>
                </div>
            </a>
        </div>
    }
}

MusicCenter.App/Views/Shared/_ConcertCalendarPopup.cshtml
@model List<MusicCenter.Common.ViewModels.Concert.ConcertViewModel>

@{
    var lastConcert = Model.Last();
    
    foreach (var concert in Model)
    {
    
        <a href="@Url.Action("Concert", "Concert", new { ConcertId = concert.ConcertId, BandName = concert.BandName })" style="text-decoration:none">
            <div class="row">
                <div class="col-sm-3">
                    <img src="@concert.Image.PathToShow" alt="..." width="100" height="100" style="text-decoration:none">
                </div>
                <div class="col-sm-9">
                    <div class="row">
                        <div class="col-sm-2">
                            @MusicCenter.Common.Resources.Global.Bands:
                        </div>
                        <div class="col-sm-10">
                            @{
                                var lastBand = concert.Bands.Last();

                                foreach (var item in concert.Bands)
                                {
                                    if (item.Equals(lastBand))
	                                {
		                                <div style="display:inline">@item.BandName</div>
	                                }
                                    else
                                    {
                                        <div style="display:inline">@item.BandName , </div>
                                    }
                                }
		                                
	                        }                
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-2">
                            @MusicCenter.Common.Resources.Global.Address:
                        </div>
                        <div class="col-sm-10">
                            @concert.address
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            @MusicCenter.Common.Resources.Global.InterestedUsers:
                        </div>
                        <div class="col-sm-6">
                            @concert.InterestedCount
                        </div>
                    </div>
                </div>
            </div>
        </a>
    
        if (!concert.Equals(lastConcert))
        {
            <hr />
        }    
    
    }
}
    

MusicCenter.App/Views/Shared/_ConcertTable.cshtml
@model PagedList<MusicCenter.Common.ViewModels.Concert.ConcertListItemViewModel>

<div class="row">
    <div class="col-sm-2">

    </div>
    <div class="col-sm-2">
        @MusicCenter.Common.Resources.Global.Bands
    </div>
    <div class="col-sm-2">
        @MusicCenter.Common.Resources.Global.Genres
    </div>
    <div class="col-sm-2">
        @MusicCenter.Common.Resources.Global.Address
    </div>
    <div class="col-sm-2">
        @MusicCenter.Common.Resources.Global.Date
    </div>
</div>

@foreach (var concert in Model)
{
    <div class="row">
        <a href="@Url.Action("Concert", "Concert", new { ConcertId = concert.Id, BandName = concert.ConcertOwner})" style="text-decoration: none;">
            <div class="col-sm-2">
                <img src="@concert.Image.PathToShow" class="img-circle" width="50" height="50" style="margin-left: 5px">
            </div>
            <div class="col-sm-2">
                @if (concert.BandNames != null)
                {
                    if (concert.BandNames.Count > 3)
                    {
                        <div>@String.Join(",", concert.BandNames.Take(3).ToArray())</div>
                    }
                    else
                    {
                        <div>@String.Join(",", concert.BandNames.ToArray())</div>
                    }
                }
            </div>
            <div class="col-sm-2">
                @if (concert.Genres != null)
                {
                    if (concert.Genres.Count > 3)
                    {
                        <div>@String.Join(",", concert.Genres.Take(3).ToArray())</div>
                    }
                    else
                    {
                        <div>@String.Join(",", concert.Genres.ToArray())</div>
                    }
                }
            </div>
            <div class="col-sm-2">
                @concert.Address
            </div>
            <div class="col-sm-2">
                @Html.DisplayFor(c => concert.Date)
            </div>
        </a>
        @{
            var controllerName = HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString();

            if (Session["user"] != null && controllerName == "Concert")
            {
                <div class="col-sm-2">
                    <input type="button" name="AddConcertToFavBtn" data-concertid="@concert.Id" class="btn btn-success" value="@MusicCenter.Common.Resources.Global.AddToFavourites" />
                </div>
            }
            else if (Session["user"] != null && controllerName == "Favourites")
            {
                <div class="col-sm-2">
                    <input type="button" name="DeleteConcertFav" data-concertid="@concert.Id" class="btn btn-danger" value="@MusicCenter.Common.Resources.Global.Delete" />
                </div>
            }

        }
    </div>
}
<div id="concertListData" data-user="@Session["user"]" data-addtofavurl="@Url.Action("AddConcertToFavourites", "Favourites")" data-checkfavurl="@Url.Action("IsUserHaveConcertsInFavourites", "Favourites")" />

MusicCenter.App/Views/Shared/_FavouriteAlbumsPartial.cshtml
@model PagedList<MusicCenter.Common.ViewModels.Band.AlbumListItemViewModel>

@{ Html.RenderPartial("_AlbumTable", Model); }

<div style="bottom:0; position:fixed; width:100%; text-align:center;">
    @Ajax.Pager(Model, new PagerOptions { ActionName = "UserFavouriteAlbums", ControllerName = "Favourites", CurrentPagerItemTemplate = "<li class='active'><a href='#'>{0}</a></li>", DisabledPagerItemTemplate = "<li class='disabled'><a>{0}</a></li>", PageIndexParameterName = "albumsPageId", FirstPageText = @MusicCenter.Common.Resources.Global.First, LastPageText = @MusicCenter.Common.Resources.Global.Last, NextPageText = @MusicCenter.Common.Resources.Global.Next, PrevPageText = @MusicCenter.Common.Resources.Global.Previous, ContainerTagName = "ul", CssClass = "pagination", PagerItemTemplate = "<li name='pagerPage'>{0}</li>" }).AjaxOptions(a => a.SetUpdateTargetId("albumList"))
</div>

MusicCenter.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@MusicCenter.Common.Resources.Global.AppName</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryValidation")
    @Scripts.Render("~/bundles/unobtrusive")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/Layout/LoginPanel.js")
    @Scripts.Render("~/Scripts/Layout/UserPanel.js")
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")

    @RenderSection("scripts", required: false)
    <script src="https://connect.soundcloud.com/sdk/sdk-3.1.2.js"></script>
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav" style="height: 25px">
                    <li class="navbar-header">
                        @Html.ActionLink(MusicCenter.Common.Resources.Global.AppName, "Index", "Home", null, new { @class = "navbar-brand" })
                    </li>
                    <li>
                        @Html.ActionLink(MusicCenter.Common.Resources.Global.ChangeLanguagePl, "SetCulture", "Home", new { @culture = "pl" }, null)
                    </li>
                    <li>
                        @Html.ActionLink(MusicCenter.Common.Resources.Global.ChangeLanguageEn, "SetCulture", "Home", new { @culture = "en" }, null)
                    </li>
                </ul>
                    @if (Session["user"] != null || Session["band"] != null)
                    {
                        if (Session["band"] != null)
                        {
                            @Html.Action("GetBandPanel", "Band")
                        }
                        else
                        {
                            @Html.Action("GetUserPanel", "User")
                        }

                    }
                    else
                    {
                        @Html.Action("GetLoginPanel", "Account")
                    }
                <br />
                <br />
                <br/>
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink(MusicCenter.Common.Resources.Global.Bands, "BandList", "Band")</li>
                    <li>@Html.ActionLink(MusicCenter.Common.Resources.Global.Albums, "AlbumList", "Band")</li>
                    <li>@Html.ActionLink(MusicCenter.Common.Resources.Global.Songs, "SongList", "Band")</li>
                    <li>@Html.ActionLink(MusicCenter.Common.Resources.Global.Concerts, "ConcertList", "Concert")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @Html.Partial("_SearchPanel")
                </ul>                
            </div>
            
        </div>
    </div>
    <div class="container body-content">
        <br/>
        <br/>
        <br/>
        @RenderBody()
        <hr />
    </div>
</body>
</html>

MusicCenter.App/Views/Shared/_UserLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/User/UserPage.css")

<div id="sidebar-wrapper">
    <ul class="sidebar-nav">
        <li>
            <a href="#" id="UserProfile">@MusicCenter.Common.Resources.Global.Profile</a>
        </li>
        <li>
            <a href="@Url.Action("UserMessages", "Message")" id="UserMessages">@MusicCenter.Common.Resources.Global.Messages</a>
        </li>
        <li>
            <a href="@Url.Action("UserFavourites", "Favourites")" id="UserFavourites">@MusicCenter.Common.Resources.Global.Favourites</a>
        </li>
        <li>
            <a href="@Url.Action("UserBands", "Band")" id="UserBands">@MusicCenter.Common.Resources.Global.YourBands</a>
        </li>
    </ul>
</div>

<div style="position:relative; left: 50px">@RenderBody()</div>

<script>
    $(document).ready(function () {

        if (localStorage['scToken'] != null) {
            $("#UserProfile").attr("href", '@Url.Action("UserSoundcloudProfile", "User")')
        }
        else {
            $("#UserProfile").attr("href", '@Url.Action("UserProfile", "User")')
        }


    })
</script>