MusicCenter.App/Controllers/BandController.cs
using MusicCenter.App.Filters;
using MusicCenter.Common.RequestModels;
using MusicCenter.Common.ViewModels.Band;
using MusicCenter.Services.Intefaces;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;

namespace MusicCenter.App.Controllers
{
    public class BandController : BaseController
    {
        IBandService bandService;

        public BandController(IBandService serv)
        {
            bandService = serv;
        }

        public PartialViewResult RenderBandLayout(string BandName)
        {
            return PartialView("_BandLayout", BandName);
        }

        [UserAuthorize]
        public ActionResult UserBands()
        {
            List<BandListItemViewModel> userBands = bandService.GetUserBandList(Session["user"].ToString());

            return View(userBands);
        }

        public ActionResult AddBand()
        {
            return View();
        }

        [HttpPost]
        [UserAuthorize]
        public ActionResult AddBand(AddBandViewModel model)
        {
            if (model.Avatar.PostedFile != null)
            {
                string trailingPath = model.Avatar.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Avatar.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid)
            {
                if (!bandService.IfBandExists(model.Name))
                {
                    model.UserEmail = Session["user"].ToString();
                    bandService.AddBand(model);
                }
            }

            return RedirectToAction("UserBands");
        }

        [BandAuthorize]
        public ActionResult GetBandPanel()
        {
            BandPanelViewModel model = new BandPanelViewModel();
            model = bandService.GetBandPanelViewModelByName(Session["band"].ToString());

            return PartialView("_BandPanel", model);
        }

        public ActionResult BandProfile(string BandName)
        {
            BandProfileViewModel model = bandService.GetBandProfileViewModel(BandName);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult BandProfile(BandProfileViewModel model)
        {
            if (model.Avatar.PostedFile != null)
            {
                string trailingPath = model.Avatar.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Avatar.RelativePathToSave = fullPath;
            }

            if (bandService.IsVisitorBandOwner(Session["band"].ToString(), model.BandId))
            {
                if (ModelState.IsValid)
                {
                    bandService.EditBandProfile(model);
                }
            }

            model = bandService.GetBandProfileViewModel(model.Name);

            return View(model);
        }

        public ActionResult BandAlbums(string BandName)
        {
            BandAlbumListViewModel albumList = bandService.GetBandAlbums(BandName);

            return View(albumList);
        }

        public ActionResult BandSingles(string BandName)
        {
            BandSingleListViewModel model = bandService.GetBandSingleListViewModel(BandName);

            return View(model);
        }


        [BandAuthorize]
        public ActionResult AddAlbum()
        {
            AddAlbumViewModel model = new AddAlbumViewModel();
            model.BandName = Session["band"].ToString();

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult AddAlbum(AddAlbumViewModel model)
        {
            if (model.Cover.PostedFile != null)
            {
                string trailingPath = model.Cover.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Cover.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid && model.SongsNames.Length > 0)
            {
                bandService.AddAlbum(model);
            }
            
            return View(model);
        }

        public ActionResult Album(string AlbumName)
        {
            AlbumViewModel model = bandService.GetAlbumViewModelByName(AlbumName);
 
            return View(model);
        }

        [HttpGet]
        [BandAuthorize]
        public ActionResult UpdateAlbum(string AlbumName)
        {
            UpdateAlbumViewModel model = bandService.GetUpdateAlbumViewModel(AlbumName);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult UpdateAlbum(UpdateAlbumViewModel model)
        {
            if (model.Cover.PostedFile != null)
            {
                string trailingPath = model.Cover.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Cover.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid)
            {
                bandService.UpdateAlbum(model);
            }

            model = bandService.GetUpdateAlbumViewModel(model.Name);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult DeleteAlbum(string AlbumName)
        {
            if (bandService.IsVisitorAlbumOwner(Session["band"].ToString(), AlbumName))
            {
                bandService.DeleteAlbum(AlbumName);
            }
            
            return RedirectToAction("BandAlbums");
        }

        [BandAuthorize]
        public ActionResult AddSingle()
        {
            AddSingleViewModel model = new AddSingleViewModel();
            model.BandName = Session["band"].ToString();

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult AddSingle(AddSingleViewModel model)
        {
            if (ModelState.IsValid && !String.IsNullOrEmpty(model.SongName))
            {
                bandService.AddSingle(model);
            }

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult DeleteSingle(int SingleId)
        {
            bandService.DeleteSingle(SingleId);

            return RedirectToAction("BandSingles");
        }

        [BandAuthorize]
        public ActionResult UpdateSingle(int SingleId)
        {
            BandSingleViewModel model = bandService.GetBandSingleViewModel(SingleId);
            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult UpdateSingle(BandSingleViewModel model)
        {
            if (ModelState.IsValid)
            {
                bandService.UpdateSingle(model);
            }
            model = bandService.GetBandSingleViewModel(model.Id);
            return View(model);
        }

        public JsonResult GetAllBandNames()
        {
            return Json(bandService.GetAllBandNames(), JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult GetBandsPanel()
        {
            List<BandsPanelViewModel> model = bandService.GetNewestBands();

            return PartialView("_BandsPanel", model);
        }

        public PartialViewResult GetAlbumsPanel()
        {
            List<AlbumsPanelViewModel> model = bandService.GetNewestAlbums();

            return PartialView("_AlbumsPanel", model);
        }

        public PartialViewResult GetSongsPanel()
        {
            List<SongsPanelViewModel> model = bandService.GetNewestSingles();

            return PartialView("_SongsPanel", model);
        }

        public ActionResult Single(int SingleId)
        {
            var model = bandService.GetBandSingleViewModel(SingleId);

            return View(model);
        }
        
        [HttpGet]
        public ActionResult BandList(int id = 1)
        {
            string dateFrom = this.Request.QueryString["DateFrom"];
            string dateTo = this.Request.QueryString["DateTo"];

            DataListFilterModel filter = new DataListFilterModel()
            {
                Names = this.Request.QueryString["Names"],
                GenreNames = this.Request.QueryString["GenreNames"],
                DateFrom = string.IsNullOrEmpty(dateFrom) ? (DateTime?)null : DateTime.Parse(dateFrom),
                DateTo = string.IsNullOrEmpty(dateTo) ? (DateTime?)null : DateTime.Parse(dateTo)
            };

            var model = bandService.GetBandListByPageNuber(filter, id);
            if (Request.IsAjaxRequest())
                return PartialView("_BandListPartial", model);
            return View(model);
        }

        [HttpGet]
        public ActionResult AlbumList(int id = 1)
        {
            string dateFrom = this.Request.QueryString["DateFrom"];
            string dateTo = this.Request.QueryString["DateTo"];

            DataListFilterModel filter = new DataListFilterModel()
            {
                Names = this.Request.QueryString["Names"],
                GenreNames = this.Request.QueryString["GenreNames"],
                DateFrom = string.IsNullOrEmpty(dateFrom) ? (DateTime?)null : DateTime.Parse(dateFrom),
                DateTo = string.IsNullOrEmpty(dateTo) ? (DateTime?)null : DateTime.Parse(dateTo)
            };

            var model = bandService.GetAlbumListByPageNuber(filter, id);

MusicCenter.App/Controllers/FavouritesController.cs
using MusicCenter.App.Filters;
using MusicCenter.Common.ViewModels.Band;
using MusicCenter.Common.ViewModels.Concert;
using MusicCenter.Services.Intefaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;

namespace MusicCenter.App.Controllers
{
    public class FavouritesController : BaseController
    {
        IFavouritesService favServ;

        public FavouritesController(IFavouritesService serv)
        {
            favServ = serv;
        }

        [UserAuthorize]
        public ActionResult UserFavourites()
        {
            return View();
        }

        [HttpPost]
        [UserAuthorize]
        public void AddAlbumToFavourites(string AlbumName)
        {
            favServ.AddAlbumToFavourites(Session["user"].ToString(), AlbumName);
        }

        [HttpPost]
        [UserAuthorize]
        public void AddSongToFavourites(int SongId)
        {
            favServ.AddSongToFavourites(Session["user"].ToString(), SongId);
        }

        [HttpPost]
        [UserAuthorize]
        public void AddBandToFavourites(string BandName)
        {
            favServ.AddBandToFavourites(Session["user"].ToString(), BandName);
        }

        [HttpPost]
        [UserAuthorize]
        public JsonResult IsUserHaveBandsInFavourites(List<string> BandNames)
        {
            var result = favServ.IsUserHaveBandsInFavourites(Session["user"].ToString(), BandNames);

            return Json(result);
        }

        [HttpPost]
        [UserAuthorize]
        public bool IsUserHaveAlbumInFavourites(string AlbumName)
        {
            return favServ.IsUserHaveAlbumInFavourites(Session["user"].ToString(), AlbumName);
        }

        [HttpPost]
        [UserAuthorize]
        public JsonResult IsUserHaveAlbumsInFavourites(List<string> AlbumNames)
        {
            var result = favServ.IsUserHaveAlbumsInFavourites(Session["user"].ToString(), AlbumNames);

            return Json(result);
        }

        [HttpPost]
        [UserAuthorize]
        public bool IsUserHaveSongInFavourites(int SongId)
        {
            return favServ.IsUserHaveSongInFavourites(Session["user"].ToString(), SongId);
        }

        [HttpPost]
        [UserAuthorize]
        public JsonResult IsUserHaveSongsInFavourites(List<int> SongIds)
        {
            var result = favServ.IsUserHaveSongsInFavourites(Session["user"].ToString(), SongIds);

            return Json(result);
        }

        [HttpPost]
        [UserAuthorize]
        public JsonResult IsUserHaveConcertsInFavourites(List<int> ConcertIds)
        {
            var result = favServ.IsUserHaveConcertsInFavourites(Session["user"].ToString(), ConcertIds);

            return Json(result);
        }

        [HttpPost]
        [UserAuthorize]
        public void AddConcertToFavourites(int ConcertId)
        {
            favServ.AddConcertToFavourites(Session["user"].ToString(), ConcertId);
        }

        [HttpGet]
        [UserAuthorize]
        public ActionResult UserFavouriteBands(int bandPageId = 1)
        {
            PagedList<BandListItemViewModel> model = favServ.GetUserFavouriteBandsByPageNumber(bandPageId, Session["user"].ToString());
            if (Request.IsAjaxRequest())
                return PartialView("_FavouriteBandsPartial", model);
            return View(model);
        }

        [HttpGet]
        [UserAuthorize]
        public ActionResult UserFavouriteAlbums(int albumsPageId = 1)
        {
            PagedList<AlbumListItemViewModel> model = favServ.GetUserFavouriteAlbumsByPageNumber(albumsPageId, Session["user"].ToString());
            if (Request.IsAjaxRequest())
                return PartialView("_FavouriteAlbumsPartial", model);
            return View(model);
        }

        [HttpGet]
        [UserAuthorize]
        public ActionResult UserFavouriteSongs(int songsPageId = 1)
        {
            PagedList<SongListItemViewModel> model = favServ.GetUserFavouriteSongsByPageNumber(songsPageId, Session["user"].ToString());
            if (Request.IsAjaxRequest())
                return PartialView("_FavouriteSongsPartial", model);
            return View(model);
        }

        [HttpGet]
        [UserAuthorize]
        public ActionResult UserFavouriteConcerts(int concertsPageId = 1)
        {
            PagedList<ConcertListItemViewModel> model = favServ.GetUserFavouriteConcertsByPageNumber(concertsPageId, Session["user"].ToString());
            if (Request.IsAjaxRequest())
                return PartialView("_FavouriteConcertsPartial", model);
            return View(model);
        }

    }
}

MusicCenter.App/Views/Band/AddAlbum.cshtml
@model MusicCenter.Common.ViewModels.Band.AddAlbumViewModel

@Styles.Render("~/Content/Account/Register.css")
@Styles.Render("~/Content/Band/AddAlbum.css")
@Scripts.Render("~/Scripts/Band/AddAlbum.js")
@Scripts.Render("~/Scripts/jquery-ui-1.11.4.js")
@Scripts.Render("~/Scripts/jquery.form.js")

<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.0/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />

      @Html.Action("RenderBandLayout", "Band", new { BandName = @Model.BandName })
<div id="BodyContent" style="margin-left: 50px; margin-top: 10px">
    <form id="AddAlbumForm" enctype="multipart/form-data" >
          @Html.HiddenFor(m => m.BandName)
        <div class="row form-group">
            <div class="col-md-2">
                <img src="~/Content/Uploads/DefaultAlbumAv.jpg" alt="..." class="img-rounded" style="display:block;margin-left:auto;margin-right:auto;" width="150" height="150" id="albumCover">
            </div>
            <div class="col-lg-10">
                <div class="row form-group">
                    <div class="col-sm-1">
                        <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Name:</label>
                    </div>
                    <div class="col-sm-2">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control input-sm" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                    <div class="col-sm-2">
                        <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.ReleaseDate:</label>
                    </div>
                    <div class="col-sm-2">
                        @Html.TextBoxFor(m => m.ReleaseDate, new { @class = "form-control input-sm", id = "ReleaseDate" })
                        @Html.ValidationMessageFor(m => m.ReleaseDate)
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-1">
                        <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Label:</label>
                    </div>
                    <div class="col-sm-2">
                        @Html.TextBoxFor(m => m.Label, new { @class = "form-control input-sm" })
                    </div>
                    <div class="col-sm-2">
                        <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Producer:</label>
                    </div>
                    <div class="col-sm-2">
                        @Html.TextBoxFor(m => m.Producer, new { @class = "form-control input-sm" })
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-1">
                        <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Genres:</label>
                    </div>
                    <div class="col-sm-6">
                        @Html.TextBoxFor(m => m.Genres, new { @class = "form-control input-sm", name = "Genres", placeholder = @MusicCenter.Common.Resources.Global.SeparatedByComma, style = "max-width: none" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-1" style="margin-left:40px">
                <span class="btn btn-primary btn-file">
                    @MusicCenter.Common.Resources.Global.Browse @Html.TextBoxFor(m => m.Cover.PostedFile, new { type = "file", name = "Cover", @class = "input-sm", @id = "cover" })
                </span>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-1">
                <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Songs:</label>
            </div>
            <div class="col-sm-11">
                <div class="row form-group">
                    <div class="col-sm-10">
                        <input id="songInput" type="file" multiple class="file" data-overwrite-initial="false" name="songInput">
                        <div id="songInput_validate" style="color:darkred"></div>
                    </div>
                </div>
            </div>
        </div>
        <input type="button" id="CreateAlbumBtn" class="btn btn-default pull-right" value="@MusicCenter.Common.Resources.Global.Create" />
    </form>
</div>

MusicCenter.App/Views/Band/Album.cshtml
@model MusicCenter.Common.ViewModels.Band.AlbumViewModel

@Html.Action("RenderBandLayout", "Band", new { BandName = @Model.BandName })
@Scripts.Render("~/Scripts/Band/Album.js")
<div id="BodyContent" style="margin-left: 50px; margin-top: 10px">
        <div class="row form-group">
            <div class="col-md-2">
                <img src="@Model.CoverPath" alt="..." class="img-rounded" style="display:block;margin-left:auto;margin-right:auto;" width="150" height="150" id="albumCover">
            </div>
            <div class="col-lg-10">
                <div class="row form-group">
                    <div class="col-md-2">
                        <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Name:</label>
                    </div>
                    <div class="col-md-2">
                        @Model.Name
                    </div>
                    <div class="col-md-2">
                        <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.ReleaseDate:</label>
                    </div>
                    <div class="col-md-2">
                        @Html.DisplayFor(m => m.ReleaseDate)
                    </div>
                    @if (Session["user"] != null)
                    {
                        <div class="col-md-2">
                            <input type="button" id="AddAlbumToFavBtn" data-checkurl="@Url.Action("IsUserHaveAlbumInFavourites", "Favourites")" data-url="@Url.Action("AddAlbumToFavourites", "Favourites")" name="@Model.Name" value="@MusicCenter.Common.Resources.Global.AddToFavourites" class="btn btn-default" />
                        </div>
                    }
                </div>
                <div class="row form-group">
                    <div class="col-md-2">
                        <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Label:</label>
                    </div>
                    <div class="col-md-2">
                        @Model.Label
                    </div>
                    <div class="col-md-2">
                        <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Producer:</label>
                    </div>
                    <div class="col-md-2">
                        @Model.Producer
                    </div>                  
                </div>
                <div class="row form-group">
                    <div class="col-md-2">
                        <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Genres:</label>
                    </div>
                    <div class="col-md-6">
                        @Model.Genres
                    </div>
                </div>
            </div>
        </div>
        <div class="row form-group">
            <div class="col-sm-1">
                <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Songs:</label>
            </div>
            <div class="col-sm-11">
                @foreach (var item in Model.Songs)
                {
                    var songUrl = @item.UrlAddress;
                         
                    <div class="row form-group">
                        <div class="col-sm-8" >
                            <iframe width="100%" height="20" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/@songUrl&amp;color=ff5500&amp;inverse=false&amp;auto_play=false&amp;show_user=false"></iframe>
                        </div>
                        @if (Session["user"] != null)
                        {
                            <div class="col-sm-2">
                                <input type="button" id="@item.Id" data-checkurl="@Url.Action("IsUserHaveSongInFavourites", "Favourites")" data-url="@Url.Action("AddSongToFavourites", "Favourites")" name="AddSongToFav" value="@MusicCenter.Common.Resources.Global.AddToFavourites" class="btn btn-default btn-sm" />
                            </div>
                        }
                    </div>
                }
            </div>
        </div>
</div>

MusicCenter.App/Views/Band/BandSingles.cshtml
@model MusicCenter.Common.ViewModels.Band.BandSingleListViewModel


@Html.Action("RenderBandLayout", "Band", new { BandName = @Model.BandName })
@Scripts.Render("~/Scripts/Band/BandSingles.js")
<div id="BodyContent" style="margin-left: 50px">
    <ul class="nav nav-tabs" style="margin-bottom:10px">
        <li role="presentation"><a href="@Url.Action("BandAlbums", "Band", new { BandName = @Model.BandName })">@MusicCenter.Common.Resources.Global.Albums</a></li>
        <li role="presentation" class="active"><a href="@Url.Action("BandSingles", "Band", new { BandName = @Model.BandName })">@MusicCenter.Common.Resources.Global.Songs</a></li>
    </ul>

    
        @foreach (var Single in Model.Singles)
        {
            <div class="row">
                <div class="col-sm-10">
                    <div class="thumbnail">
                        <iframe width="100%" height="20" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/@Single.UrlAddress&amp;color=ff5500&amp;inverse=false&amp;auto_play=false&amp;show_user=false"></iframe>
                        <div class="caption">
                            <p>@MusicCenter.Common.Resources.Global.Genres: @Single.Genres</p>
                            <p>@MusicCenter.Common.Resources.Global.ReleaseDate: @Html.DisplayFor(m => Single.ReleaseDate)</p>
                        </div>
                    </div>
                    @if (Session["band"] != null && Session["band"].ToString() == Model.BandName)
                    {
                        <div class="row form-group">
                            <div class="col-sm-1">
                                <input type="button" data-url="@Url.Action("UpdateSingle", "Band", new { SingleId = @Single.Id})" class="btn btn-default" value="@MusicCenter.Common.Resources.Global.Edit" name="EditSingleBtn" />
                            </div>
                            <div class="col-sm-1">
                                <input type="button" data-singleid="@Single.Id" data-singlename="@Single.Name" class="btn btn-default" value="@MusicCenter.Common.Resources.Global.Delete" data-toggle="modal" data-target="#confirm-submit" name="DeleteSingleBtn" />
                            </div>
                        </div>
                    }
                </div>
                @if (Session["user"] != null)
                {
                    <div class="col-sm-2">
                        <input type="button" class="btn btn-default" data-checkurl="@Url.Action("IsUserHaveSongInFavourites", "Favourites")" data-url="@Url.Action("AddSongToFavourites", "Favourites")" value="@MusicCenter.Common.Resources.Global.AddToFavourites" id="@Single.Id" name="AddSongToFavBtn" />
                    </div>
                }     
            </div>
        }
        @if (Session["band"] != null && Session["band"].ToString() == Model.BandName)
        {
            <div class="row pull-right">
                <a href="@Url.Action("AddSingle", "Band")" class="btn btn-default">@MusicCenter.Common.Resources.Global.AddSong</a>
            </div>
        }
        
    <div class="modal fade" id="confirm-submit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    @MusicCenter.Common.Resources.Global.Confirm
                </div>
                <div class="modal-body">
                    @MusicCenter.Common.Resources.Global.ConfirmDelete <b><p style="display:inline" id="SingleName"></p></b> ?
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">@MusicCenter.Common.Resources.Global.Cancel</button>
                    <button data-url="@Url.Action("DeleteSingle", "Band")" id="DeleteConfirmBtn" class="btn btn-success success">OK</button>
                </div>
            </div>
        </div>

    </div>

</div>

MusicCenter.App/Views/Band/Single.cshtml
@model MusicCenter.Common.ViewModels.Band.BandSingleViewModel

@Html.Action("RenderBandLayout", "Band", new { BandName = @Model.BandName })

<div id="BodyContent" style="margin-left: 50px">
    <div class="row">
        <div class="col-sm-10">
            <div class="thumbnail">
                <iframe width="100%" height="20" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/@Model.UrlAddress&amp;color=ff5500&amp;inverse=false&amp;auto_play=false&amp;show_user=false"></iframe>
                <div class="caption">
                    <p>@MusicCenter.Common.Resources.Global.Genres: @Model.Genres</p>
                    <p>@MusicCenter.Common.Resources.Global.ReleaseDate: @Html.DisplayFor(m => m.ReleaseDate)</p>
                </div>
            </div>
            @if (Session["band"] != null && Session["band"].ToString() == Model.BandName)
            {
                <div class="row form-group">
                    <div class="col-sm-1">
                        <input type="button" data-url="@Url.Action("UpdateSingle", "Band", new { SingleId = @Model.Id})" class="btn btn-default" value="@MusicCenter.Common.Resources.Global.Edit" name="EditSingleBtn" />
                    </div>
                    <div class="col-sm-1">
                        <input type="button" data-singleid="@Model.Id" data-singlename="@Model.Name" class="btn btn-default" value="@MusicCenter.Common.Resources.Global.Delete" data-toggle="modal" data-target="#confirm-submit" name="DeleteSingleBtn" />
                    </div>
                </div>
            }
        </div>
        @if (Session["user"] != null)
        {
            <div class="col-sm-2">
                <input type="button" class="btn btn-default" data-checkurl="@Url.Action("IsUserHaveSongInFavourites", "Favourites")" data-url="@Url.Action("AddSongToFavourites", "Favourites")" value="@MusicCenter.Common.Resources.Global.AddToFavourites" id="@Model.Id" name="AddSongToFavBtn" />
            </div>
        }
    </div>
</div>

MusicCenter.App/Views/Band/UpdateSingle.cshtml
@model MusicCenter.Common.ViewModels.Band.BandSingleViewModel

@Scripts.Render("~/Scripts/Band/UpdateSingle.js")
@Scripts.Render("~/Scripts/jquery-ui-1.11.4.js")
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.0/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />

@Html.Action("RenderBandLayout", "Band", new { BandName = @Model.BandName })

<div id="BodyContent" style="margin-left: 50px; margin-top: 10px">
    <form action="@Url.Action("UpdateSingle", "Band")" method="post">
        @Html.HiddenFor(m => m.Id)
        <div class="col-sm-12">
            <div class="row form-group">
                <iframe width="100%" height="20" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/@Model.UrlAddress&amp;color=ff5500&amp;inverse=false&amp;auto_play=false&amp;show_user=false"></iframe>
            </div>
            <div class="row form-group">
                <div class="col-sm-1">
                    @MusicCenter.Common.Resources.Global.Genres:
                </div>
                <div class="col-sm-11">
                    @Html.TextBoxFor(m => m.Genres, new { @class = "form-control" })
                </div>
            </div>
            <div class="row form-group">
                <div class="col-sm-2">
                    @MusicCenter.Common.Resources.Global.ReleaseDate:
                </div>
                <div class="col-sm-2" style="left: -90px" >
                    @Html.TextBoxFor(m => m.ReleaseDate, "{0:d}", new { @class = "form-control", @id = "ReleaseDate" })
                </div>
            </div>
        </div>
        <input type="submit" value="@MusicCenter.Common.Resources.Global.Save" class="btn btn-default pull-right" />
    </form>
</div>