MusicCenter.App/Controllers/BandController.cs
using MusicCenter.App.Filters;
using MusicCenter.Common.RequestModels;
using MusicCenter.Common.ViewModels.Band;
using MusicCenter.Services.Intefaces;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;

namespace MusicCenter.App.Controllers
{
    public class BandController : BaseController
    {
        IBandService bandService;

        public BandController(IBandService serv)
        {
            bandService = serv;
        }

        public PartialViewResult RenderBandLayout(string BandName)
        {
            return PartialView("_BandLayout", BandName);
        }

        [UserAuthorize]
        public ActionResult UserBands()
        {
            List<BandListItemViewModel> userBands = bandService.GetUserBandList(Session["user"].ToString());

            return View(userBands);
        }

        public ActionResult AddBand()
        {
            return View();
        }

        [HttpPost]
        [UserAuthorize]
        public ActionResult AddBand(AddBandViewModel model)
        {
            if (model.Avatar.PostedFile != null)
            {
                string trailingPath = model.Avatar.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Avatar.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid)
            {
                if (!bandService.IfBandExists(model.Name))
                {
                    model.UserEmail = Session["user"].ToString();
                    bandService.AddBand(model);
                }
            }

            return RedirectToAction("UserBands");
        }

        [BandAuthorize]
        public ActionResult GetBandPanel()
        {
            BandPanelViewModel model = new BandPanelViewModel();
            model = bandService.GetBandPanelViewModelByName(Session["band"].ToString());

            return PartialView("_BandPanel", model);
        }

        public ActionResult BandProfile(string BandName)
        {
            BandProfileViewModel model = bandService.GetBandProfileViewModel(BandName);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult BandProfile(BandProfileViewModel model)
        {
            if (model.Avatar.PostedFile != null)
            {
                string trailingPath = model.Avatar.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Avatar.RelativePathToSave = fullPath;
            }

            if (bandService.IsVisitorBandOwner(Session["band"].ToString(), model.BandId))
            {
                if (ModelState.IsValid)
                {
                    bandService.EditBandProfile(model);
                }
            }

            model = bandService.GetBandProfileViewModel(model.Name);

            return View(model);
        }

        public ActionResult BandAlbums(string BandName)
        {
            BandAlbumListViewModel albumList = bandService.GetBandAlbums(BandName);

            return View(albumList);
        }

        public ActionResult BandSingles(string BandName)
        {
            BandSingleListViewModel model = bandService.GetBandSingleListViewModel(BandName);

            return View(model);
        }


        [BandAuthorize]
        public ActionResult AddAlbum()
        {
            AddAlbumViewModel model = new AddAlbumViewModel();
            model.BandName = Session["band"].ToString();

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult AddAlbum(AddAlbumViewModel model)
        {
            if (model.Cover.PostedFile != null)
            {
                string trailingPath = model.Cover.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Cover.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid && model.SongsNames.Length > 0)
            {
                bandService.AddAlbum(model);
            }
            
            return View(model);
        }

        public ActionResult Album(string AlbumName)
        {
            AlbumViewModel model = bandService.GetAlbumViewModelByName(AlbumName);
 
            return View(model);
        }

        [HttpGet]
        [BandAuthorize]
        public ActionResult UpdateAlbum(string AlbumName)
        {
            UpdateAlbumViewModel model = bandService.GetUpdateAlbumViewModel(AlbumName);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult UpdateAlbum(UpdateAlbumViewModel model)
        {
            if (model.Cover.PostedFile != null)
            {
                string trailingPath = model.Cover.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Cover.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid)
            {
                bandService.UpdateAlbum(model);
            }

            model = bandService.GetUpdateAlbumViewModel(model.Name);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult DeleteAlbum(string AlbumName)
        {
            if (bandService.IsVisitorAlbumOwner(Session["band"].ToString(), AlbumName))
            {
                bandService.DeleteAlbum(AlbumName);
            }
            
            return RedirectToAction("BandAlbums");
        }

        [BandAuthorize]
        public ActionResult AddSingle()
        {
            AddSingleViewModel model = new AddSingleViewModel();
            model.BandName = Session["band"].ToString();

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult AddSingle(AddSingleViewModel model)
        {
            if (ModelState.IsValid && !String.IsNullOrEmpty(model.SongName))
            {
                bandService.AddSingle(model);
            }

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult DeleteSingle(int SingleId)
        {
            bandService.DeleteSingle(SingleId);

            return RedirectToAction("BandSingles");
        }

        [BandAuthorize]
        public ActionResult UpdateSingle(int SingleId)
        {
            BandSingleViewModel model = bandService.GetBandSingleViewModel(SingleId);
            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult UpdateSingle(BandSingleViewModel model)
        {
            if (ModelState.IsValid)
            {
                bandService.UpdateSingle(model);
            }
            model = bandService.GetBandSingleViewModel(model.Id);
            return View(model);
        }

        public JsonResult GetAllBandNames()
        {
            return Json(bandService.GetAllBandNames(), JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult GetBandsPanel()
        {
            List<BandsPanelViewModel> model = bandService.GetNewestBands();

            return PartialView("_BandsPanel", model);
        }

        public PartialViewResult GetAlbumsPanel()
        {
            List<AlbumsPanelViewModel> model = bandService.GetNewestAlbums();

            return PartialView("_AlbumsPanel", model);
        }

        public PartialViewResult GetSongsPanel()
        {
            List<SongsPanelViewModel> model = bandService.GetNewestSingles();

            return PartialView("_SongsPanel", model);
        }

        public ActionResult Single(int SingleId)
        {
            var model = bandService.GetBandSingleViewModel(SingleId);

            return View(model);
        }
        
        [HttpGet]
        public ActionResult BandList(int id = 1)
        {
            string dateFrom = this.Request.QueryString["DateFrom"];
            string dateTo = this.Request.QueryString["DateTo"];

            DataListFilterModel filter = new DataListFilterModel()
            {
                Names = this.Request.QueryString["Names"],
                GenreNames = this.Request.QueryString["GenreNames"],
                DateFrom = string.IsNullOrEmpty(dateFrom) ? (DateTime?)null : DateTime.Parse(dateFrom),
                DateTo = string.IsNullOrEmpty(dateTo) ? (DateTime?)null : DateTime.Parse(dateTo)
            };

            var model = bandService.GetBandListByPageNuber(filter, id);
            if (Request.IsAjaxRequest())
                return PartialView("_BandListPartial", model);
            return View(model);
        }

        [HttpGet]
        public ActionResult AlbumList(int id = 1)
        {
            string dateFrom = this.Request.QueryString["DateFrom"];
            string dateTo = this.Request.QueryString["DateTo"];

            DataListFilterModel filter = new DataListFilterModel()
            {
                Names = this.Request.QueryString["Names"],
                GenreNames = this.Request.QueryString["GenreNames"],
                DateFrom = string.IsNullOrEmpty(dateFrom) ? (DateTime?)null : DateTime.Parse(dateFrom),
                DateTo = string.IsNullOrEmpty(dateTo) ? (DateTime?)null : DateTime.Parse(dateTo)
            };

            var model = bandService.GetAlbumListByPageNuber(filter, id);

MusicCenter.App/Controllers/ConcertController.cs
using MusicCenter.App.Filters;
using MusicCenter.Common.RequestModels;
using MusicCenter.Common.ViewModels.Concert;
using MusicCenter.Services.Intefaces;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicCenter.App.Controllers
{
    public class ConcertController : BaseController
    {
        private IConcertService _concertService;

        public ConcertController(IConcertService service)
        {
            _concertService = service;
        }

        public ActionResult BandConcerts(string BandName)
        {
            BandConcertListViewModel model = _concertService.GetBandConcertListViewModel(BandName);

            return View(model);
        }

        public ActionResult Concert(int ConcertId, string BandName)
        {
            ConcertViewModel model = _concertService.GetConcertViewModel(ConcertId);
            model.BandName = BandName;

            return View(model);
        }

        [BandAuthorize]
        public ActionResult AddConcert()
        {
            AddConcertViewModel model = new AddConcertViewModel();
            model.BandName = Session["band"].ToString();

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult AddConcert(AddConcertViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Cover.PostedFile != null)
                {
                    string trailingPath = model.Cover.PostedFile.FileName;
                    string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                    model.Cover.RelativePathToSave = fullPath;
                }

                _concertService.AddConcert(model);
            }

            return View(model);
        }

        [BandAuthorize]
        public ActionResult UpdateConcert(int ConcertId)
        {

            UpdateConcertViewModel model = _concertService.GetUpdateConcertViewModel(ConcertId);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult UpdateConcert(UpdateConcertViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (model.Cover.PostedFile != null)
                {
                    string trailingPath = model.Cover.PostedFile.FileName;
                    string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                    model.Cover.RelativePathToSave = fullPath;
                }

                _concertService.UpdateConcert(model);
            }

            model = _concertService.GetUpdateConcertViewModel(model.ConcertId);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult DeleteConcert(int ConcertId)
        {
            if (_concertService.IsVisitorConcertOwner(Session["band"].ToString(), ConcertId))
            {
                _concertService.DeleteConcert(ConcertId);
            }

            return RedirectToAction("BandConcerts");
        }

        public PartialViewResult GetBandDetailsRemovablePartial(string BandName)
        {
            BandConcertViewModel model = _concertService.GetBandConcertViewModel(BandName);

            return PartialView("BandDetailsRemovable", model);
        }

        public PartialViewResult GetBandDetailsPartial(string BandName)
        {
            BandConcertViewModel model = _concertService.GetBandConcertViewModel(BandName);

            return PartialView("BandDetails", model);
        }

        public PartialViewResult GetCalendarPanel()
        {
            //List<CalendarItemViewModel> model = _concertService.GetCalendarPanelViewModel();

            return PartialView("_CalendarPanel");
        }

        public ActionResult GetConcerts(int year, int month)
        {
            //List<CalendarPanelViewModel> model = _concertService.GetCalendarPanelViewModel();
            var concertList = _concertService.GetConcertsInMonth(year, month);

            var concertCalendarList = GetCalendarItems(concertList);

            return Json(concertCalendarList, JsonRequestBehavior.AllowGet);
        }
        
        public List<CalendarItemViewModel> GetCalendarItems(List<ConcertViewModel> concerts)
        {
            List<CalendarItemViewModel> calendarItems = new List<CalendarItemViewModel>() ;

            //concertsInDay = concerts.gro
            foreach (ConcertViewModel concert in concerts)
            {
                List<ConcertViewModel> concertsInDay = new List<ConcertViewModel>();

                concertsInDay.AddRange(concerts.Where(c => c.date.ToShortDateString() == concert.date.ToShortDateString()).ToList());

                if (!calendarItems.Any(c => c.date == concert.date.ToString("yyyy-MM-dd")))
                {
                    calendarItems.Add(new CalendarItemViewModel()
                    {
                        badge = true,
                        date = concert.date.ToString("yyyy-MM-dd"),
                        title = "Concerts on " + concert.date.ToLongDateString(),
                        footer = "",
                        classname = "purple-event",
                        body = RenderRazorViewToString("_ConcertCalendarPopup", concertsInDay)
                    });
                }
                
            }

            return calendarItems; 
        }

        [HttpGet]
        public ActionResult ConcertList(int id = 1)
        {
            string dateFrom = this.Request.QueryString["DateFrom"];
            string dateTo = this.Request.QueryString["DateTo"];

            DataListFilterModel filter = new DataListFilterModel()
            {
                Names = this.Request.QueryString["Names"],
                GenreNames = this.Request.QueryString["GenreNames"],
                DateFrom = string.IsNullOrEmpty(dateFrom) ? (DateTime?)null : DateTime.Parse(dateFrom),
                DateTo = string.IsNullOrEmpty(dateTo) ? (DateTime?)null : DateTime.Parse(dateTo)
            };

            var model = _concertService.GetConcertListByPageNuber(filter, id);
            if (Request.IsAjaxRequest())
                return PartialView("_ConcertListPartial", model);
            return View(model);
        }

    }
}

MusicCenter.App/Views/Concert/AddConcert.cshtml
@model MusicCenter.Common.ViewModels.Concert.AddConcertViewModel

@Scripts.Render("~/Scripts/Concert/AddConcert.js")
@Styles.Render("~/Content/Account/Register.css")
@Scripts.Render("~/Scripts/jquery-ui-1.11.4.js")
@Scripts.Render("~/Scripts/jquery.datetimepicker.full.min.js")
@Styles.Render("~/Content/datetimepicker.css")
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.0/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCCkA4CEGdy_2RRIyooD80al_-NCgxr_Tg&libraries=places"></script>

@Html.Action("RenderBandLayout", "Band", new { BandName = @Model.BandName })

<div id="BodyContent" style="margin-left: 50px">
    <ul class="nav nav-tabs" style="margin-bottom:10px">
        <li role="presentation" id="DetailsTab" class="active"><a href="#">@MusicCenter.Common.Resources.Global.Details</a></li>
        <li role="presentation" id="LocalizationTab"><a href="#">@MusicCenter.Common.Resources.Global.Localization</a></li>
    </ul>

    <form id="AddConcertForm" action="@Url.Action("AddConcert", "Concert")" method="post" enctype="multipart/form-data">
        @Html.HiddenFor(m => m.BandName)
        @Html.HiddenFor(m => m.Latitude, new { @id = "Latitude" })
        @Html.HiddenFor(m => m.Longitude, new { @id = "Longitude" })
        <div class="row" id="DetailsPanel">
            <div class="row form-group">
                <div class="col-md-2">
                    <div class="row">
                        <img src="~/Content/Uploads/DefaultConcertAv.jpg" alt="..." class="img-rounded" style="display:block;margin-left:auto;margin-right:auto;" width="150" height="150" id="concertCover">
                    </div>
                    <div class="row" style="margin-top: 20px">
                        <div class="col-sm-1" style="margin-left:40px">
                            <span class="btn btn-primary btn-file">
                                @MusicCenter.Common.Resources.Global.Browse @Html.TextBoxFor(m => m.Cover.PostedFile, new { type = "file", name = "Cover", @class = "input-sm", @id = "cover" })
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-10">
                    <div class="row form-group">
                        <div class="col-sm-1">
                            <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Date:</label>
                        </div>
                        <div class="col-sm-3">
                            @Html.TextBoxFor(m => m.date, new { @class = "form-control input-sm", id = "Date" })
                            @Html.ValidationMessageFor(m => m.date)
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-sm-1">
                            <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Bands:</label>
                        </div>
                        <div class="col-sm-3">
                            <input id="BandSelect" data-url="@Url.Action("GetAllBandNames", "Band")" placeholder="@MusicCenter.Common.Resources.Global.EnterBandNames" class="form-control"></input>
                            <div id="menu-container" style="position:absolute; z-index: 99999"></div>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-sm-1">

                        </div>
                        <div class="col-sm-11" id="BandsContainer" data-url="@Url.Action("GetBandDetailsRemovablePartial", "Concert")">
                            <div>
                                @Html.Action("GetBandDetailsPartial", new { BandName = Model.BandName })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-sm-11" style="margin-left: 140px">
                    <div class="col-sm-1">
                        <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Description:</label>
                    </div>
                    <div class="col-sm-10" style="margin-left:20px">
                        @Html.TextAreaFor(m => m.description, new { @class = "form-control", @style = "max-width:100%", @rows = "5" })
                    </div>
                </div>
            </div>
        </div>
        <div id="LocalizationPanel" style="visibility: hidden; width: 0px; height: 0px">
                @Html.TextBoxFor(m => m.address, new { @placeholder = @MusicCenter.Common.Resources.Global.SearchAddress, @id = "search-input", @class = "form-control" } )
                <div id="map" style="height:400px; width:100%">

                </div>
        </div>          
        <input type="button" id="CreateConcertBtn" class="btn btn-default pull-right" value="@MusicCenter.Common.Resources.Global.Create" />
    </form>
</div>

MusicCenter.App/Views/Concert/BandConcerts.cshtml
@model MusicCenter.Common.ViewModels.Concert.BandConcertListViewModel

@Scripts.Render("~/Scripts/Concert/BandConcerts.js")

@Html.Action("RenderBandLayout", "Band", new { BandName = @Model.BandName })

<div id="BodyContent" style="margin-left: 50px">
    <div class="row">
        @foreach (var Concert in Model.Concerts)
        {
            <div class="col-sm-2 col-md-4">
                <a href="@Url.Action("Concert", "Concert", new {ConcertId = Concert.Id, BandName = Model.BandName })" style="text-decoration:none">
                    <div class="thumbnail">
                        <img src="@Concert.Cover.PathToShow" alt="...">
                        <div class="caption">
                            <p>@MusicCenter.Common.Resources.Global.Date: @Html.DisplayFor(m => Concert.date)</p>
                            <p>@MusicCenter.Common.Resources.Global.Address: @Concert.address</p>
                            <p>@MusicCenter.Common.Resources.Global.InterestedUsers: @Concert.InterestedCount</p>
                        </div>
                    </div>
                </a>
                @if (Session["band"] != null && Session["band"].ToString() == Concert.ConcertOwner)
                {
                    <div class="row form-group">
                        <div class="col-sm-2">
                            <input type="button" data-url="@Url.Action("UpdateConcert", "Concert", new { ConcertId = @Concert.Id})" class="btn btn-default" value="@MusicCenter.Common.Resources.Global.Edit" name="EditConcertBtn" />
                        </div>
                        <div class="col-sm-2">
                            <input type="button" data-concertid="@Concert.Id" data-address="@Concert.address" class="btn btn-default" value="@MusicCenter.Common.Resources.Global.Delete" data-toggle="modal" data-target="#confirm-submit" name="DeleteConcertBtn" />
                        </div>
                    </div>
                }
            </div>
        }
    </div>
    @if (Session["band"] != null && Session["band"].ToString() == Model.BandName)
    {
        <div class="row pull-right">
            <a href="@Url.Action("AddConcert", "Concert")" class="btn btn-default">@MusicCenter.Common.Resources.Global.AddConcert</a>
        </div>
    }

    <div class="modal fade" id="confirm-submit" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    @MusicCenter.Common.Resources.Global.Confirm
                </div>
                <div class="modal-body">
                    @MusicCenter.Common.Resources.Global.ConfirmDeleteConcert <b><p style="display:inline" id="ConcertAddr"></p></b> ?
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">@MusicCenter.Common.Resources.Global.Cancel</button>
                    <button data-url="@Url.Action("DeleteConcert", "Concert")" id="DeleteConfirmBtn" class="btn btn-success success">OK</button>
                </div>
            </div>
        </div>
    </div>

MusicCenter.App/Views/Concert/ConcertList.cshtml
@model PagedList<MusicCenter.Common.ViewModels.Concert.ConcertListItemViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Html.Partial("_DataFilter", "ConcertList")

<div id="dataList">
    @Html.Partial("_ConcertListPartial", Model)
</div>
@section scripts
{
    @Scripts.Render("~/Scripts/Concert/ConcertList.js")
    @Scripts.Render("~/Scripts/Layout/DataFilter.js")
    @{Html.RegisterMvcPagerScriptResource();}
}

MusicCenter.App/Views/Concert/UpdateConcert.cshtml
@model MusicCenter.Common.ViewModels.Concert.UpdateConcertViewModel

@Html.Action("RenderBandLayout", "Band", new { BandName = @Model.BandName })

@Scripts.Render("~/Scripts/Concert/UpdateConcert.js")
@Styles.Render("~/Content/Account/Register.css")
@Scripts.Render("~/Scripts/jquery-ui-1.11.4.js")
@Scripts.Render("~/Scripts/jquery.datetimepicker.full.min.js")
@Styles.Render("~/Content/datetimepicker.css")
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.0/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCCkA4CEGdy_2RRIyooD80al_-NCgxr_Tg&libraries=places"></script>

<div id="BodyContent" style="margin-left: 50px">
    <ul class="nav nav-tabs" style="margin-bottom:10px">
        <li role="presentation" id="DetailsTab" class="active"><a href="#">@MusicCenter.Common.Resources.Global.Details</a></li>
        <li role="presentation" id="LocalizationTab"><a href="#">@MusicCenter.Common.Resources.Global.Localization</a></li>
    </ul>
    <form id="UpdateConcertForm" action="@Url.Action("UpdateConcert", "Concert")" method="post" enctype="multipart/form-data">
        @Html.HiddenFor(m => m.ConcertId)
        @Html.HiddenFor(m => m.BandName)
        @Html.HiddenFor(m => m.Latitude, new { @id = "Latitude" })
        @Html.HiddenFor(m => m.Longitude, new { @id = "Longitude" })
        <div class="row" id="DetailsPanel">
            <div class="row form-group">
                <div class="col-md-2">
                    <div class="row">
                        <img src="@Model.Cover.PathToShow" alt="..." class="img-rounded" style="display:block;margin-left:auto;margin-right:auto;" width="150" height="150" id="concertCover">
                    </div>
                    <div class="row" style="margin-top: 20px">
                        <div class="col-sm-1" style="margin-left:40px">
                            <span class="btn btn-primary btn-file">
                                @MusicCenter.Common.Resources.Global.Browse @Html.TextBoxFor(m => m.Cover.PostedFile, new { type = "file", name = "Cover", @class = "input-sm", @id = "cover" })
                            </span>
                        </div>
                    </div>
                </div>
                <div class="col-lg-10">
                    <div class="row form-group">
                        <div class="col-sm-1">
                            <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Date:</label>
                        </div>
                        <div class="col-sm-3">
                            @Html.TextBoxFor(m => m.date, new { @class = "form-control input-sm", id = "Date" })
                            @Html.ValidationMessageFor(m => m.date)
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-sm-1">
                            <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Bands:</label>
                        </div>
                        <div class="col-sm-3">
                            <input id="BandSelect" data-url="@Url.Action("GetAllBandNames", "Band")" placeholder="@MusicCenter.Common.Resources.Global.EnterBandNames" class="form-control"></input>
                            <div id="menu-container" style="position:absolute; z-index: 99999"></div>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-sm-1">

                        </div>
                        <div class="col-sm-11" id="BandsContainer" data-url="@Url.Action("GetBandDetailsRemovablePartial", "Concert")">
                            <div>
                                @Html.Action("GetBandDetailsPartial", new { BandName = Model.BandName })
                            </div>

                            @foreach (var band in Model.Bands)
                            {
                                <div>
                                    @Html.Action("GetBandDetailsRemovablePartial", new { BandName = band})
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-sm-11" style="margin-left: 140px">
                    <div class="col-sm-1">
                        <label class="control-label input-sm">@MusicCenter.Common.Resources.Global.Description:</label>
                    </div>
                    <div class="col-sm-10" style="margin-left:20px">
                        @Html.TextAreaFor(m => m.description, new { @class = "form-control", @style = "max-width:100%", @rows = "5" })
                    </div>
                </div>
            </div>
        </div>
        <div id="LocalizationPanel" style="visibility: hidden; width: 0px; height: 0px">
            @Html.TextBoxFor(m => m.address, new { @placeholder = @MusicCenter.Common.Resources.Global.SearchAddress, @style = "max-width:100%; width: 100%", @id = "search-input", @class = "form-control" })
            <div id="map" style="height:400px; width:100%">

            </div>
        </div>
        <input type="button" id="UpdateConcertBtn" class="btn btn-default pull-right" value="@MusicCenter.Common.Resources.Global.Save" />
    </form>
</div>