MusicCenter.App/Controllers/BandController.cs
using MusicCenter.App.Filters;
using MusicCenter.Common.RequestModels;
using MusicCenter.Common.ViewModels.Band;
using MusicCenter.Services.Intefaces;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;

namespace MusicCenter.App.Controllers
{
    public class BandController : BaseController
    {
        IBandService bandService;

        public BandController(IBandService serv)
        {
            bandService = serv;
        }

        public PartialViewResult RenderBandLayout(string BandName)
        {
            return PartialView("_BandLayout", BandName);
        }

        [UserAuthorize]
        public ActionResult UserBands()
        {
            List<BandListItemViewModel> userBands = bandService.GetUserBandList(Session["user"].ToString());

            return View(userBands);
        }

        public ActionResult AddBand()
        {
            return View();
        }

        [HttpPost]
        [UserAuthorize]
        public ActionResult AddBand(AddBandViewModel model)
        {
            if (model.Avatar.PostedFile != null)
            {
                string trailingPath = model.Avatar.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Avatar.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid)
            {
                if (!bandService.IfBandExists(model.Name))
                {
                    model.UserEmail = Session["user"].ToString();
                    bandService.AddBand(model);
                }
            }

            return RedirectToAction("UserBands");
        }

        [BandAuthorize]
        public ActionResult GetBandPanel()
        {
            BandPanelViewModel model = new BandPanelViewModel();
            model = bandService.GetBandPanelViewModelByName(Session["band"].ToString());

            return PartialView("_BandPanel", model);
        }

        public ActionResult BandProfile(string BandName)
        {
            BandProfileViewModel model = bandService.GetBandProfileViewModel(BandName);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult BandProfile(BandProfileViewModel model)
        {
            if (model.Avatar.PostedFile != null)
            {
                string trailingPath = model.Avatar.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Avatar.RelativePathToSave = fullPath;
            }

            if (bandService.IsVisitorBandOwner(Session["band"].ToString(), model.BandId))
            {
                if (ModelState.IsValid)
                {
                    bandService.EditBandProfile(model);
                }
            }

            model = bandService.GetBandProfileViewModel(model.Name);

            return View(model);
        }

        public ActionResult BandAlbums(string BandName)
        {
            BandAlbumListViewModel albumList = bandService.GetBandAlbums(BandName);

            return View(albumList);
        }

        public ActionResult BandSingles(string BandName)
        {
            BandSingleListViewModel model = bandService.GetBandSingleListViewModel(BandName);

            return View(model);
        }


        [BandAuthorize]
        public ActionResult AddAlbum()
        {
            AddAlbumViewModel model = new AddAlbumViewModel();
            model.BandName = Session["band"].ToString();

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult AddAlbum(AddAlbumViewModel model)
        {
            if (model.Cover.PostedFile != null)
            {
                string trailingPath = model.Cover.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Cover.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid && model.SongsNames.Length > 0)
            {
                bandService.AddAlbum(model);
            }
            
            return View(model);
        }

        public ActionResult Album(string AlbumName)
        {
            AlbumViewModel model = bandService.GetAlbumViewModelByName(AlbumName);
 
            return View(model);
        }

        [HttpGet]
        [BandAuthorize]
        public ActionResult UpdateAlbum(string AlbumName)
        {
            UpdateAlbumViewModel model = bandService.GetUpdateAlbumViewModel(AlbumName);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult UpdateAlbum(UpdateAlbumViewModel model)
        {
            if (model.Cover.PostedFile != null)
            {
                string trailingPath = model.Cover.PostedFile.FileName;
                string fullPath = Path.Combine(Server.MapPath("\\Content\\Uploads\\"), trailingPath);

                model.Cover.RelativePathToSave = fullPath;
            }

            if (ModelState.IsValid)
            {
                bandService.UpdateAlbum(model);
            }

            model = bandService.GetUpdateAlbumViewModel(model.Name);

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult DeleteAlbum(string AlbumName)
        {
            if (bandService.IsVisitorAlbumOwner(Session["band"].ToString(), AlbumName))
            {
                bandService.DeleteAlbum(AlbumName);
            }
            
            return RedirectToAction("BandAlbums");
        }

        [BandAuthorize]
        public ActionResult AddSingle()
        {
            AddSingleViewModel model = new AddSingleViewModel();
            model.BandName = Session["band"].ToString();

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult AddSingle(AddSingleViewModel model)
        {
            if (ModelState.IsValid && !String.IsNullOrEmpty(model.SongName))
            {
                bandService.AddSingle(model);
            }

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult DeleteSingle(int SingleId)
        {
            bandService.DeleteSingle(SingleId);

            return RedirectToAction("BandSingles");
        }

        [BandAuthorize]
        public ActionResult UpdateSingle(int SingleId)
        {
            BandSingleViewModel model = bandService.GetBandSingleViewModel(SingleId);
            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult UpdateSingle(BandSingleViewModel model)
        {
            if (ModelState.IsValid)
            {
                bandService.UpdateSingle(model);
            }
            model = bandService.GetBandSingleViewModel(model.Id);
            return View(model);
        }

        public JsonResult GetAllBandNames()
        {
            return Json(bandService.GetAllBandNames(), JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult GetBandsPanel()
        {
            List<BandsPanelViewModel> model = bandService.GetNewestBands();

            return PartialView("_BandsPanel", model);
        }

        public PartialViewResult GetAlbumsPanel()
        {
            List<AlbumsPanelViewModel> model = bandService.GetNewestAlbums();

            return PartialView("_AlbumsPanel", model);
        }

        public PartialViewResult GetSongsPanel()
        {
            List<SongsPanelViewModel> model = bandService.GetNewestSingles();

            return PartialView("_SongsPanel", model);
        }

        public ActionResult Single(int SingleId)
        {
            var model = bandService.GetBandSingleViewModel(SingleId);

            return View(model);
        }
        
        [HttpGet]
        public ActionResult BandList(int id = 1)
        {
            string dateFrom = this.Request.QueryString["DateFrom"];
            string dateTo = this.Request.QueryString["DateTo"];

            DataListFilterModel filter = new DataListFilterModel()
            {
                Names = this.Request.QueryString["Names"],
                GenreNames = this.Request.QueryString["GenreNames"],
                DateFrom = string.IsNullOrEmpty(dateFrom) ? (DateTime?)null : DateTime.Parse(dateFrom),
                DateTo = string.IsNullOrEmpty(dateTo) ? (DateTime?)null : DateTime.Parse(dateTo)
            };

            var model = bandService.GetBandListByPageNuber(filter, id);
            if (Request.IsAjaxRequest())
                return PartialView("_BandListPartial", model);
            return View(model);
        }

        [HttpGet]
        public ActionResult AlbumList(int id = 1)
        {
            string dateFrom = this.Request.QueryString["DateFrom"];
            string dateTo = this.Request.QueryString["DateTo"];

            DataListFilterModel filter = new DataListFilterModel()
            {
                Names = this.Request.QueryString["Names"],
                GenreNames = this.Request.QueryString["GenreNames"],
                DateFrom = string.IsNullOrEmpty(dateFrom) ? (DateTime?)null : DateTime.Parse(dateFrom),
                DateTo = string.IsNullOrEmpty(dateTo) ? (DateTime?)null : DateTime.Parse(dateTo)
            };

            var model = bandService.GetAlbumListByPageNuber(filter, id);

MusicCenter.App/Controllers/MessageController.cs
using MusicCenter.App.Filters;
using MusicCenter.Common.ViewModels.Message;
using MusicCenter.Services.Intefaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicCenter.App.Controllers
{
    public class MessageController : Controller
    {
        IMessageService msgService;

        public MessageController(IMessageService serv)
        {
            msgService = serv;
        }

        [UserAuthorize]
        public ActionResult UserMessages()
        {
            List<MessageLisItemViewModel> userMessages = msgService.GetUserReceivedMessages(Session["user"].ToString());

            return View(userMessages);
        }

        [UserAuthorize]
        public ActionResult UserSentMessages()
        {
            List<MessageLisItemViewModel> userMessages = msgService.GetUserSentMessages(Session["user"].ToString());

            return View(userMessages);
        }

        [UserAuthorize]
        public ActionResult UserNewMessage(int? MessageId)
        {
            NewMessageViewModel model = new NewMessageViewModel();

            if (MessageId.HasValue)
            {
                model = msgService.GetNewMessageViewModel(MessageId);
            }

            return View(model);
        }

        [HttpPost]
        [UserAuthorize]
        public ActionResult UserNewMessage(NewMessageViewModel model)
        {
            model.AuthorEmail = Session["user"].ToString();

            if (ModelState.IsValid)
            {
                if (msgService.MessageRecipientsValid(model.Recipients))
                {
                    msgService.SendMessage(model);

                    return RedirectToAction("UserSentMessages");
                    
                }
                else
                {
                    model.RecipientsErrorMsg = "Some of recipients doeas not exists";
                }

            }
            return View(model);
        }

        [UserAuthorize]
        public ActionResult UserMessageDetails(int MessageId)
        {
            MessageDetailsViewModel model = msgService.GetMessageDetailsViewModel(MessageId);
            if (!Session["user"].ToString().ToLower().Equals(model.Author.ToLower()))
            {
                msgService.SetMessageReaded(model.Id);
            }
            return View(model);
        }

        [BandAuthorize]
        public ActionResult BandMessages()
        {
            List<MessageLisItemViewModel> bandMsgs = msgService.GetBandReceivedMessages(Session["band"].ToString());

            return View(bandMsgs);
        }

        [BandAuthorize]
        public ActionResult BandSentMessages()
        {
            List<MessageLisItemViewModel> bandMessages = msgService.GetBandSentMessages(Session["band"].ToString());

            return View(bandMessages);
        }

        [BandAuthorize]
        public ActionResult BandNewMessage(int? MessageId)
        {
            NewMessageViewModel model = new NewMessageViewModel();

            if (MessageId.HasValue)
            {
                model = msgService.GetNewMessageViewModel(MessageId);
            }

            return View(model);
        }

        [HttpPost]
        [BandAuthorize]
        public ActionResult BandNewMessage(NewMessageViewModel model)
        {
            model.AuthorEmail = Session["band"].ToString();

            if (ModelState.IsValid)
            {
                if (msgService.MessageRecipientsValid(model.Recipients))
                {
                    msgService.SendMessage(model);

                    return RedirectToAction("BandSentMessages");
                }
                else
                {
                    model.RecipientsErrorMsg = "Some of recipients doeas not exists";
                }

            }
            return View(model);
        }

        [BandAuthorize]
        public ActionResult BandMessageDetails(int MessageId)
        {
            MessageDetailsViewModel model = msgService.GetMessageDetailsViewModel(MessageId);
            if (!Session["band"].ToString().ToLower().Equals(model.Author.ToLower()))
            {
                msgService.SetMessageReaded(model.Id);
            }
            return View(model);
        }

        [SessionAuthorize]
        public ActionResult SendBandMessage(string Recipient)
        {
            NewMessageViewModel model = new NewMessageViewModel();
            model.Recipients = Recipient;

            if (Session["user"] != null)
            {
                model.AuthorEmail = Session["user"].ToString();
            }
            else
            {
                model.AuthorEmail = Session["band"].ToString();
            }

            return View(model);
        }

        [HttpPost]
        [SessionAuthorize]
        public ActionResult SendBandMessage(NewMessageViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (msgService.MessageRecipientsValid(model.Recipients))
                {
                    msgService.SendMessage(model);
                    return View(model);
                }
                else
                {
                    model.RecipientsErrorMsg = "Some of recipients doeas not exists";
                }

            }

            return View(model);
        }
	}
}

MusicCenter.App/Views/Message/BandMessageDetails.cshtml
@model MusicCenter.Common.ViewModels.Message.MessageDetailsViewModel

@{
    Html.RenderAction("RenderBandLayout", "Band", new { BandName = Session["band"].ToString() });
}
<div id="BodyContent" style="margin-left: 50px">

    <ul class="nav nav-tabs" style="margin-bottom:10px">
        <li role="presentation"><a href="@Url.Action("BandMessages", "Message")">@MusicCenter.Common.Resources.Global.Received</a></li>
        <li role="presentation"><a href="@Url.Action("BandSentMessages", "Message")">@MusicCenter.Common.Resources.Global.Sent</a></li>
        <li role="presentation" class="active"><a href="@Url.Action("BandNewMessage", "Message")">@MusicCenter.Common.Resources.Global.NewMessage</a></li>
    </ul>

    <div class="form-group">
        <label>@MusicCenter.Common.Resources.Global.Author</label>
        @Html.TextBoxFor(m => m.Author, new { @class = "form-control", disabled = "disabled", @placeholder = @MusicCenter.Common.Resources.Global.SeparatedByComma })
    </div>
    <div class="form-group">
        <label>@MusicCenter.Common.Resources.Global.Title</label>
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control", disabled = "disabled" })
        @Html.ValidationMessageFor(m => m.Title)
    </div>
    <div class="form-group">
        <label>@MusicCenter.Common.Resources.Global.Message</label>
        @Html.TextAreaFor(m => m.Content, new { @class = "form-control", disabled = "disabled", @rows = "4" })
    </div>
    <div class="form-group">
        <a class="btn btn-default" href="@Url.Action("BandNewMessage", "Message", new { MessageId = @Model.Id })" role="button">@MusicCenter.Common.Resources.Global.Reply</a>
    </div>
</div>






MusicCenter.App/Views/Message/BandMessages.cshtml
@model List<MusicCenter.Common.ViewModels.Message.MessageLisItemViewModel>

@{
    Html.RenderAction("RenderBandLayout", "Band", new { BandName = Session["band"].ToString() });
}
<div id="BodyContent" style="margin-left: 50px">
    <ul class="nav nav-tabs" style="margin-bottom:10px">
        <li role="presentation" class="active"><a href="@Url.Action("BandMessages", "Message")">Received</a></li>
        <li role="presentation"><a href="@Url.Action("BandSentMessages", "Message")">Sent</a></li>
        <li role="presentation"><a href="@Url.Action("BandNewMessage", "Message")">New message</a></li>
    </ul>
    <div class="row">
        <div class="col-md-2">
            @MusicCenter.Common.Resources.Global.Author
        </div>
        <div class="col-md-2">
            @MusicCenter.Common.Resources.Global.Date
        </div>
        <div class="col-md-2">
            @MusicCenter.Common.Resources.Global.Title
        </div>
        <div class="col-md-2">
            @MusicCenter.Common.Resources.Global.Recipients
        </div>
        <div class="col-md-2">
            @MusicCenter.Common.Resources.Global.Readed
        </div>
    </div>

    @if (Model.Count > 0)
    {
        foreach (var item in Model)
        {
            if (!item.IsReaded)
            {
                <div class="row" style="background:lightblue">
                    <div class="col-md-2">
                        @item.Author
                    </div>
                    <div class="col-md-2">
                        @item.SentDate
                    </div>
                    <div class="col-md-2">
                        @item.Title
                    </div>
                    <div class="col-md-2">
                        @item.Recipients
                    </div>
                    <div class="col-md-1">
                        @if (item.IsReaded)
                        {<label>@MusicCenter.Common.Resources.Global.Yes</label>}
                        else
                        {<label>@MusicCenter.Common.Resources.Global.No</label>}
                    </div>
                    <div class="col-md-1">
                        <a class="btn btn-default" href="@Url.Action("BandMessageDetails", "Message", new { MessageId = @item.Id })" role="button">@MusicCenter.Common.Resources.Global.Details</a>
                    </div>
                </div>
            }
            else
            {
                <div class="row">
                    <div class="col-md-2">
                        @item.Author
                    </div>
                    <div class="col-md-2">
                        @item.SentDate
                    </div>
                    <div class="col-md-2">
                        @item.Title
                    </div>
                    <div class="col-md-2">
                        @item.Recipients
                    </div>
                    <div class="col-md-1">
                        @if (item.IsReaded)
                        {<label>@MusicCenter.Common.Resources.Global.Yes</label>}
                        else
                        {<label>@MusicCenter.Common.Resources.Global.No</label>}
                    </div>
                    <div class="col-md-1">
                        <a class="btn btn-default" href="@Url.Action("BandMessageDetails", "Message", new { MessageId = @item.Id })" role="button">@MusicCenter.Common.Resources.Global.Details</a>
                    </div>
                </div>
            }

        }
    }
    else
    {
        <h1><small>No messages...</small></h1>
    }

</div>


MusicCenter.App/Views/Message/BandNewMessage.cshtml
@model MusicCenter.Common.ViewModels.Message.NewMessageViewModel

@{
    Html.RenderAction("RenderBandLayout", "Band", new { BandName = Session["band"].ToString() });
}
<div id="BodyContent" style="margin-left: 50px">

    <ul class="nav nav-tabs" style="margin-bottom:10px">
        <li role="presentation"><a href="@Url.Action("BandMessages", "Message")">@MusicCenter.Common.Resources.Global.Received</a></li>
        <li role="presentation"><a href="@Url.Action("BandSentMessages", "Message")">@MusicCenter.Common.Resources.Global.Sent</a></li>
        <li role="presentation" class="active"><a href="@Url.Action("BandNewMessage", "Message")">@MusicCenter.Common.Resources.Global.NewMessage</a></li>
    </ul>

    <form action="@Url.Action("BandNewMessage", "Message")" method="post" class="">
        <div class="form-group">
            <label>@MusicCenter.Common.Resources.Global.Recipients</label>
            @Html.TextBoxFor(m => m.Recipients, new { @class = "form-control", @placeholder = @MusicCenter.Common.Resources.Global.SeparatedByComma })
            @Html.ValidationMessageFor(m => m.Recipients)
            <div class="has-error"><div class="control-label">@Model.RecipientsErrorMsg</div></div>
        </div>
        <div class="form-group">
            <label>@MusicCenter.Common.Resources.Global.Title</label>
            @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Title)
        </div>
        <div class="form-group">
            <label>@MusicCenter.Common.Resources.Global.Message</label>
            @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "4" })
        </div>
        <div class="form-group">
            <input type="submit" value="@MusicCenter.Common.Resources.Global.Send" class="btn btn-default" />
        </div>
    </form>
</div>

MusicCenter.App/Views/Message/BandSentMessages.cshtml
@model List<MusicCenter.Common.ViewModels.Message.MessageLisItemViewModel>

@{
    Html.RenderAction("RenderBandLayout", "Band", new { BandName = Session["band"].ToString() });
}
<div id="BodyContent" style="margin-left: 50px">


    <ul class="nav nav-tabs" style="margin-bottom:10px">
        <li role="presentation"><a href="@Url.Action("BandMessages", "Message")">@MusicCenter.Common.Resources.Global.Received</a></li>
        <li role="presentation" class="active"><a href="@Url.Action("BandSentMessages", "Message")">@MusicCenter.Common.Resources.Global.Sent</a></li>
        <li role="presentation"><a href="@Url.Action("BandNewMessage", "Message")">@MusicCenter.Common.Resources.Global.NewMessage</a></li>
    </ul>
    <div class="row">
        <div class="col-md-2">
            @MusicCenter.Common.Resources.Global.Author
        </div>
        <div class="col-md-2">
            @MusicCenter.Common.Resources.Global.Date
        </div>
        <div class="col-md-2">
            @MusicCenter.Common.Resources.Global.Title
        </div>
        <div class="col-md-2">
            @MusicCenter.Common.Resources.Global.Recipients
        </div>
        <div class="col-md-2">
            @MusicCenter.Common.Resources.Global.Readed
        </div>
    </div>

    @if (Model.Count > 0)
    {
        foreach (var item in Model)
        {
            if (!item.IsReaded)
            {
                <div class="row" style="background:lightblue">
                    <div class="col-md-2">
                        @item.Author
                    </div>
                    <div class="col-md-2">
                        @item.SentDate
                    </div>
                    <div class="col-md-2">
                        @item.Title
                    </div>
                    <div class="col-md-2">
                        @item.Recipients
                    </div>
                    <div class="col-md-1">
                        @if (item.IsReaded)
                        {<label>@MusicCenter.Common.Resources.Global.Yes</label>}
                        else
                        {<label>@MusicCenter.Common.Resources.Global.No</label>}
                    </div>
                    <div class="col-md-1">
                        <a class="btn btn-default pull-right" href="@Url.Action("BandMessageDetails", "Message", new { MessageId = @item.Id })" role="button">@MusicCenter.Common.Resources.Global.Details</a>
                    </div>
                </div>
            }
            else
            {
                <div class="row">
                    <div class="col-md-2">
                        @item.Author
                    </div>
                    <div class="col-md-2">
                        @item.SentDate
                    </div>
                    <div class="col-md-2">
                        @item.Title
                    </div>
                    <div class="col-md-2">
                        @item.Recipients
                    </div>
                    <div class="col-md-1">
                        @if (item.IsReaded)
                        {<label>@MusicCenter.Common.Resources.Global.Yes</label>}
                        else
                        {<label>@MusicCenter.Common.Resources.Global.No</label>}
                    </div>
                    <div class="col-md-1">
                        <a class="btn btn-default pull-right" href="@Url.Action("BandMessageDetails", "Message", new { MessageId = @item.Id })" role="button">@MusicCenter.Common.Resources.Global.Details</a>
                    </div>
                </div>
            }

        }
    }
    else
    {
        <h1><small>No messages...</small></h1>
    }
</div>

MusicCenter.App/Views/Message/MessageDetails.cshtml
@model MusicCenter.Common.ViewModels.Message.MessageDetailsViewModel

@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<ul class="nav nav-tabs" style="margin-bottom:10px">
    <li role="presentation"><a href="@Url.Action("UserMessages", "Message")">Received</a></li>
    <li role="presentation"><a href="@Url.Action("UserSentMessages", "Message")">Sent</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("UserNewMessage", "Message")">New message</a></li>
</ul>

    <div class="form-group">
        <label>Author</label>
        @Html.TextBoxFor(m => m.Author, new { @class = "form-control", disabled="disabled", @placeholder = "separated by comma" })
    </div>
    <div class="form-group">
        <label>Title</label>
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control", disabled = "disabled" })
        @Html.ValidationMessageFor(m => m.Title)
    </div>
    <div class="form-group">
        <label>Message</label>
        @Html.TextAreaFor(m => m.Content, new { @class = "form-control", disabled="disabled", @rows = "4" })
    </div>
    <div class="form-group">
        <a class="btn btn-default" href="@Url.Action("UserNewMessage", "Message", new { MessageId = @Model.Id })" role="button">Reply</a>
    </div>

    




MusicCenter.App/Views/Message/SendBandMessage.cshtml
@model MusicCenter.Common.ViewModels.Message.NewMessageViewModel

@{
    Html.RenderAction("RenderBandLayout", "Band", new { BandName = @Model.Recipients });
}
<div id="BodyContent" style="margin-left: 50px">

    <form action="@Url.Action("SendBandMessage", "Message")" method="post" class="">
            <div class="form-group">
                <label>@MusicCenter.Common.Resources.Global.Author</label>
                @Html.TextBoxFor(m => m.AuthorEmail, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label>@MusicCenter.Common.Resources.Global.Recipients</label>
                @Html.TextBoxFor(m => m.Recipients, new { @class = "form-control", @placeholder = @MusicCenter.Common.Resources.Global .SeparatedByComma })
                @Html.ValidationMessageFor(m => m.Recipients)
                <div class="has-error"><div class="control-label">@Model.RecipientsErrorMsg</div></div>
            </div>
            <div class="form-group">
                <label>@MusicCenter.Common.Resources.Global.Title</label>
                @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Title)
            </div>
            <div class="form-group">
                <label>@MusicCenter.Common.Resources.Global.Message</label>
                @Html.TextAreaFor(m => m.Content, new { @class = "form-control", @rows = "4" })
            </div>
            <div class="form-group">
                <input type="submit" value="@MusicCenter.Common.Resources.Global.Send" class="btn btn-default" />
            </div>
</form>
</div>

MusicCenter.App/Views/Message/UserMessageDetails.cshtml
@model MusicCenter.Common.ViewModels.Message.MessageDetailsViewModel

@{
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<ul class="nav nav-tabs" style="margin-bottom:10px">
    <li role="presentation"><a href="@Url.Action("UserMessages", "Message")">@MusicCenter.Common.Resources.Global.Received</a></li>
    <li role="presentation"><a href="@Url.Action("UserSentMessages", "Message")">@MusicCenter.Common.Resources.Global.Sent</a></li>
    <li role="presentation" class="active"><a href="@Url.Action("UserNewMessage", "Message")">@MusicCenter.Common.Resources.Global.NewMessage</a></li>
</ul>

    <div class="form-group">
        <label>@MusicCenter.Common.Resources.Global.Author</label>
        @Html.TextBoxFor(m => m.Author, new { @class = "form-control", disabled="disabled", @placeholder = "separated by comma" })
    </div>
    <div class="form-group">
        <label>@MusicCenter.Common.Resources.Global.Title</label>
        @Html.TextBoxFor(m => m.Title, new { @class = "form-control", disabled = "disabled" })
        @Html.ValidationMessageFor(m => m.Title)
    </div>
    <div class="form-group">
        <label>@MusicCenter.Common.Resources.Global.Message</label>
        @Html.TextAreaFor(m => m.Content, new { @class = "form-control", disabled="disabled", @rows = "4" })
    </div>
    <div class="form-group">
        <a class="btn btn-default" href="@Url.Action("UserNewMessage", "Message", new { MessageId = @Model.Id })" role="button">@MusicCenter.Common.Resources.Global.Reply</a>
    </div>

    


